"""added

Revision ID: 1a781caa7327
Revises: 3a5acd12d1df
Create Date: 2023-09-24 03:00:13.981807

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a781caa7327'
down_revision: Union[str, None] = '3a5acd12d1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('file_path', sa.String(
                        length=255), nullable=True),
                    sa.Column('with_file', sa.Boolean(), nullable=False),
                    sa.Column('file_processing_status', sa.Enum('pending', 'scheduled', 'processing',
                                                                'processed', 'failed', name='note_file_processing_status'), nullable=True),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'password_hash',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default='true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('users', 'password_hash',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_table('notes')
    # ### end Alembic commands ###
